version: '3.7'
services:

  #web:
  #  container_name: nginx-python
  #  image: nginx:latest
  #  depends_on:
  #    - app-face
  #  ports:
  #    - 8085:80
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #  networks:
  #    - default

  db:
    image: postgres:latest
    container_name: face-rec-db
    ports:
      - 6000:6000
    expose:
      - 6000
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - settings_server.env
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - default

  pgadmin:
    container_name: pgadmin_agu_review
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - default

  #app-face:
  #  container_name: "app-face"
  #  image: app
  #  env_file:
  #    - settings_server.env
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  command: ["/app/docker/wait-for-it.sh", "  db:6000", "--", "/app/docker/app.sh"]
  #  ports:
  #    - "8000:8000"
  #  networks:
  #    - default
  #  depends_on:
  #    - db
  #    - pgadmin

