"""empty message

Revision ID: 3ba0f3c4639e
Revises: 1503dd7ab392
Create Date: 2024-04-02 18:45:05.835327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba0f3c4639e'
down_revision: Union[str, None] = '1503dd7ab392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('face_user_id_user_fkey', 'face_user', type_='foreignkey')
    op.drop_column('face_user', 'id_user')
    op.add_column('user', sa.Column('id_face_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'face_user', ['id_face_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'id_face_user')
    op.add_column('face_user', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('face_user_id_user_fkey', 'face_user', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###
